# Generated by Django 4.2 on 2025-12-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpressveg', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='buyer',
        ),
    ]
