# Generated by Django 4.2 on 2025-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpressveg', '0003_rename_user_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantatity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
