# Generated by Django 4.2 on 2025-12-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xpressveg', '0005_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantatity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='seller',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpressveg.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpressveg.product')),
            ],
        ),
    ]
