# Generated by Django 4.2 on 2025-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpressveg', '0007_remove_order_items_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
